### PR TITLE
Add welcome message and help alias

### PR DESCRIPTION
**Pull request by amisevsk**
### Description
Add short welcome message when starting container, and add 'help' alias that prints out installed CLIs with their versions.

web-terminal-1080

Using Chrome developer tools to simulate a 1280x720 resolution:
web-terminal-720

### How to test
From any running Web Terminal, copy and paste the following command to make the terminal update itself to this PR:
```
kubectl get dw -o json \
  -n $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) \
  $DEVWORKSPACE_NAME \
  | jq '.spec.template.components[0].plugin.components = [{
      "name": "web-terminal-tooling",
      "container": {
        "image": "quay.io/amisevsk/web-terminal-tooling:welcome-message"
      }
    }]' \
  | kubectl apply -f -
```
Once executed, the terminal will restart with the new image and you should see the welcome message and be able to type `help` for more info.

### CODE REVIEW

**Comment by serenamarie125** [comment]
This is awesome @amisevsk !

**Comment by christianvogt** [comment]
Looks great. I think my only concern is the order and whether or not we should have the command names alongside readable labels eg. `tkn (Tekton CLI) 0.19.1`

**Comment by beaumorley** [comment]
This looks really great. Copy is nice too! Agree we could order the tools. Alphabetical?

**Comment by amisevsk** [comment]
The current order is basically "the order they were added as we were developing WTO" :smile: 

I'll add descriptors (because even I forget what tool the short-name CLI is for) and reorder them. For order, I'd like to keep `oc` and `kubectl` at the top since those are immediately relevant to most users. Apart from that, maybe it makes sense to order them in some vague "popularity" order? E.g.

```
Installed tooling:
  * oc 4.9.0
  * kubectl v0.21.0-beta.1
  * helm 3.6.2
  * kn (KNative CLI) 0.23.2
  * tkn (Tekton CLI) 0.19.1
  * subctl (Submariner CLI) 0.10.1
  * odo (Red Hat OpenShift Developer CLI) v2.3.1
  * rhoas (Red Hat OpenShift Application Services CLI) 0.34.2
  * kubectx & kubens v0.9.4
  * jq
```
My thinking is 
1. Helm should come first since it's a very common tool (and doesn't get a parenthetical)
2. `kn` and `tkn` and `subctl` come second since they're likely to be familiar to users
3. `odo` and `rhoas` come third since they're Red Hat specific
4. `kubectx`, `kubens`, and `jq` come last since they're convenience tools/script wrappers

This would make it so that a user typing "help" wouldn't have to search the list for their relevant tool as much (likely nobody cares that `kubectx` and `kubens` are there, and `jq` is kind of a given)

**Comment by amisevsk** [comment]
I'm also toying with whether to display the full name or the CLI name first:

wto-options

This image can be tested by pasting 
```
export IMAGE=quay.io/amisevsk/web-terminal-tooling:welcome-options
kubectl get dw -o json \
  -n $(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace) \
  $DEVWORKSPACE_NAME \
  | jq --arg IMAGE $IMAGE '.spec.template.components[0].plugin.components = [{
      "name": "web-terminal-tooling",
      "container": {
        "image": $IMAGE
      }
    }]' \
  | kubectl apply -f -
```
in a web terminal

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
