### PR TITLE
Generate versions at build

### PR DESCRIPTION
**Pull request by amisevsk**
### Description
To support installing CLI tooling via packages instead of by direct downloads, generate the "installed tooling" help doc at build time rather than hard-coding a set of environment variables. This ensures the correct, installed version for all tooling is printed when 'help' is typed in the terminal.

For Kustomize, the downstream image no longer has a separate binary for kustomize installed. In this case, the version from `kubectl` is printed, with a note.

In addition, clean up some leftovers from earlier versions:
* Move setting PS1 into initial .bashrc instead of entrypoint.sh (holdover from before tooling image had built-in .bashrc)
* Generate odo completions at build time (odo now has a `odo completions bash` command)

### How to test
```
./build.sh -i <IMAGE+TAG> -u
podman run -it --rm <IMAGE+TAG> /bin/bash
```
Verify that 
a) Typing `help` lists installed versions for installed CLIs
b) Each installed CLI's actual version matches output of `help`

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
not sure why, but building stuck for me on:
```
STEP 13: RUN for f in "${HOME}" "${INITIAL_CONFIG}" "/etc/passwd" "/etc/group"; do     echo "Changing permissions on ${f}" && chgrp -R 0 ${f} &&     chmod -R g+rwX ${f};     done &&     /tmp/get-tooling-versions.sh > /tmp/installed_tools.txt &&     echo "Installed tools:" &&     cat /tmp/installed_tools.txt &&     rm -f /tmp/get-tooling-versions.sh
Changing permissions on /home/user
Changing permissions on /tmp/initial_config
Changing permissions on /etc/passwd
Changing permissions on /etc/group
```

**Comment by amisevsk** [comment]
@ibuziuk I've tried various ways to reproduce the issue you're facing and the build always just works for me (and also in the prcheck GitHub action). 

To check if it's an issue around odo/rhoas prompting for telemetry, could you temporarily modify the Dockerfile in your local copy to just print the output of `get-tooling-versions.sh`?
```diff
  # Change permissions to let root group access necessary files
  RUN for f in "${HOME}" "${INITIAL_CONFIG}" "/etc/passwd" "/etc/group"; do \
      echo "Changing permissions on ${f}" && chgrp -R 0 ${f} && \
      chmod -R g+rwX ${f}; \
      done && \
-     /tmp/get-tooling-versions.sh > /tmp/installed_tools.txt && \
-     echo "Installed tools:" && \
-     cat /tmp/installed_tools.txt && \
-     rm -f /tmp/get-tooling-versions.sh
+     /tmp/get-tooling-versions.sh 
```

**Comment by ibuziuk** [comment]
@amisevsk same story :man_shrugging: 

```
STEP 13: RUN for f in "${HOME}" "${INITIAL_CONFIG}" "/etc/passwd" "/etc/group"; do     echo "Changing permissions on ${f}" && chgrp -R 0 ${f} &&     chmod -R g+rwX ${f};     done &&     /tmp/get-tooling-versions.sh 
Changing permissions on /home/user
Changing permissions on /tmp/initial_config
Changing permissions on /etc/passwd
Changing permissions on /etc/group
```

**Review by ibuziuk — COMMENTED** [review]
@amisevsk there might be some problem on my end, if the gh action ci pass we can probably merge

**Review by AObuchow — APPROVED** [review]
Was able to get the build to complete locally (both using podman and docker) and was able to run as well using the instructions provided in the PR.

**Pull request merged**
